/**
 * Generate Upload Traits Calldata
 *
 * This script reads traits-data.json and generates forge script commands
 * or raw calldata for uploading traits to the Traits contract.
 *
 * Usage:
 *   node script/GenerateUploadCalldata.js
 *
 * Output:
 *   - script/upload-commands.sh - Shell script with cast commands
 */

const fs = require('fs');
const path = require('path');

// Read traits data
const traitsPath = path.join(__dirname, 'traits-data.json');
const traitsData = JSON.parse(fs.readFileSync(traitsPath, 'utf8'));

// Configuration
const TRAITS_ADDRESS = process.env.TRAITS_ADDRESS || '0x_YOUR_TRAITS_CONTRACT_ADDRESS';
const RPC_URL = process.env.RPC_URL || 'https://sepolia.base.org';
const BATCH_SIZE = 5; // Upload 5 traits per transaction to stay under gas limits

/**
 * Generate shell commands for uploading traits using cast
 */
function generateCastCommands() {
    const commands = [];

    commands.push('#!/bin/bash');
    commands.push('# Auto-generated trait upload commands');
    commands.push('# Run with: bash script/upload-commands.sh');
    commands.push('');
    commands.push('# Configuration');
    commands.push(`TRAITS_ADDRESS="${TRAITS_ADDRESS}"`);
    commands.push(`RPC_URL="${RPC_URL}"`);
    commands.push('');
    commands.push('# Check for private key');
    commands.push('if [ -z "$PRIVATE_KEY" ]; then');
    commands.push('    echo "Error: PRIVATE_KEY environment variable not set"');
    commands.push('    exit 1');
    commands.push('fi');
    commands.push('');

    // Process each trait type
    for (const traitType in traitsData) {
        const typeData = traitsData[traitType];
        const traits = typeData.traits;
        const traitIds = Object.keys(traits).map(Number).sort((a, b) => a - b);

        if (traitIds.length === 0) continue;

        commands.push(`# ========================================`);
        commands.push(`# ${typeData.typeName} (Type ${traitType})`);
        commands.push(`# ========================================`);
        commands.push('');

        // Batch the uploads
        for (let i = 0; i < traitIds.length; i += BATCH_SIZE) {
            const batchIds = traitIds.slice(i, i + BATCH_SIZE);
            const batchNum = Math.floor(i / BATCH_SIZE) + 1;
            const totalBatches = Math.ceil(traitIds.length / BATCH_SIZE);

            commands.push(`echo "Uploading ${typeData.typeName} batch ${batchNum}/${totalBatches} (traits ${batchIds.join(', ')})..."`);

            // Build the arrays for the call
            const idsArray = `[${batchIds.join(',')}]`;
            const traitsArray = batchIds.map(id => {
                const trait = traits[id];
                // Escape quotes in name and png
                const name = trait.name.replace(/"/g, '\\"');
                const png = trait.png.replace(/"/g, '\\"');
                return `("${name}","${png}")`;
            }).join(',');

            // Use cast to send the transaction
            commands.push(`cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" ${traitType} "${idsArray}" "[${traitsArray}]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY`);
            commands.push('');
            commands.push('# Wait a bit to avoid nonce issues');
            commands.push('sleep 2');
            commands.push('');
        }
    }

    commands.push('echo "All traits uploaded successfully!"');

    return commands.join('\n');
}

/**
 * Generate a summary of trait counts
 */
function generateSummary() {
    console.log('\n========================================');
    console.log('Trait Upload Summary');
    console.log('========================================\n');

    let totalTraits = 0;
    let totalTransactions = 0;

    for (const traitType in traitsData) {
        const typeData = traitsData[traitType];
        const count = Object.keys(typeData.traits).length;
        if (count > 0) {
            const batches = Math.ceil(count / BATCH_SIZE);
            console.log(`  Type ${traitType} (${typeData.typeName}): ${count} traits, ${batches} transactions`);
            totalTraits += count;
            totalTransactions += batches;
        }
    }

    console.log(`\n  Total: ${totalTraits} traits in ${totalTransactions} transactions`);
    console.log(`  Batch size: ${BATCH_SIZE} traits per transaction`);
}

/**
 * Generate a Solidity file with embedded trait data for testing
 */
function generateSolidityTestData() {
    const lines = [];

    lines.push('// SPDX-License-Identifier: MIT');
    lines.push('pragma solidity ^0.8.24;');
    lines.push('');
    lines.push('import "../src/Traits.sol";');
    lines.push('');
    lines.push('/**');
    lines.push(' * @title TraitData');
    lines.push(' * @notice Auto-generated trait data for testing');
    lines.push(' * @dev Generated by GenerateUploadCalldata.js');
    lines.push(' */');
    lines.push('library TraitData {');

    // Generate a function for each trait type
    for (const traitType in traitsData) {
        const typeData = traitsData[traitType];
        const traits = typeData.traits;
        const traitIds = Object.keys(traits).map(Number).sort((a, b) => a - b);

        if (traitIds.length === 0) continue;

        // Only include first trait as sample (full data would be huge)
        const firstId = traitIds[0];
        const firstTrait = traits[firstId];

        lines.push('');
        lines.push(`    /// @notice Get sample trait for ${typeData.typeName}`);
        lines.push(`    function getSample${typeData.typeName.replace(/\s+/g, '')}() internal pure returns (`);
        lines.push('        uint8[] memory ids,');
        lines.push('        Traits.Trait[] memory data');
        lines.push('    ) {');
        lines.push('        ids = new uint8[](1);');
        lines.push(`        ids[0] = ${firstId};`);
        lines.push('        data = new Traits.Trait[](1);');
        lines.push(`        data[0] = Traits.Trait("${firstTrait.name}", "${firstTrait.png.substring(0, 100)}...");`);
        lines.push('    }');
    }

    lines.push('}');

    return lines.join('\n');
}

// Main execution
console.log('Generating trait upload scripts...\n');

// Generate and save cast commands
const castCommands = generateCastCommands();
const outputPath = path.join(__dirname, 'upload-commands.sh');
fs.writeFileSync(outputPath, castCommands);
console.log(`Generated: ${outputPath}`);

// Print summary
generateSummary();

console.log('\n========================================');
console.log('Usage Instructions');
console.log('========================================\n');
console.log('1. Deploy your Traits contract and note the address');
console.log('2. Update TRAITS_ADDRESS in upload-commands.sh');
console.log('3. Set your private key: export PRIVATE_KEY=0x...');
console.log('4. Run: bash script/upload-commands.sh');
console.log('');
