#!/bin/bash
# Auto-generated trait upload commands
# Run with: bash script/upload-commands.sh

# Configuration
TRAITS_ADDRESS="0x6CB7Ac725369023079b89beb753e1afe05C9bced"
RPC_URL="https://sepolia.base.org"

# Check for private key
if [ -z "$PRIVATE_KEY" ]; then
    echo "Error: PRIVATE_KEY environment variable not set"
    exit 1
fi

# ========================================
# Sheep Fur (Type 0)
# ========================================

echo "Uploading Sheep Fur batch 1/1 (traits 0, 1, 2, 3)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 0 "[0,1,2,3]" "[("Survivor","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAG1BMVEUAAAAAAADfvqf////U1NSgoKDaPDayjXMTERC+6f+SAAAAAXRSTlMAQObYZgAAARFJREFUKM9dzjGOwjAQBVDnBh6I19smDXX0Az2agT5SfIAIyb3TpKVbjr1jJwGJr2n89GdkU0KWqCKzpyJcgRpkt3eNHgCDu1VqAZSYe3SlIMJgZBTYUhhZCzo9oytwEz4DOoxr2XCjBMaZcQSswjUFNZ2u6RWcHE5uSEHHt0fdcUOb0uFEOmlu9Krzi5/bkpOf685UAw0bNAPlG2N4A3DXFbl94PKYFOQNlxgz8BumH5pMNaLbwVYmH/2A0SjINzD8ClSgCsJaKTc3UKGSaNedMDL38sifsHtFWDjGXZzKLdxjzlpRcSFOWqCnKUKUiDzR76xQZEnL0y/2r91hbl5P39rXawM/N9pqrdlDRPlQgX8Br1cKW3BhdQAAAABJRU5ErkJggg=="),("Black","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAAAAAABUVFTfvqcnJyeyjXMTERCh6BJhAAAAAXRSTlMAQObYZgAAAQBJREFUKM9V0NFthDAQBFCuAw+x8++RG0DoCvBqG7AQ//cT+i8hYwO5y2pliefZFfI0CgF4YLrrAVYyEuH6jiwkjZZPiU6KzArzCLjrkh2dYQSiKaAuxjygumVSbaxjAtGhS+NMBkFtkKnzUgTwryfQeqd11gywtiZTt23RVqQ9beuoZ9pi1n8DFyxA3xHfQJpGvH4AO/gflDNhHwnX0sj8hqKl/yELnOmE+dwRTZEzoNIOuBG9ZivGIOjiZjqKm54MGrLiLEWqFxsRNz2aTk2oIKnqWBEFPTKqRh2v6ZIGJOB7EwzZ2/5Ke/hZb9iW45XWcBwXpG1Rag3TXQD6ogG/hxdGus2GU1IAAAAASUVORK5CYII="),("Brown","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAACyjXMAAADfvqeUXFl3RkwTERCfc+i4AAAAAXRSTlMAQObYZgAAAQlJREFUKM9V0UGOgzAMBdCKG3yT7mMXZl84gZG5AEr2nU3vf4T5BNppLQuJp58vES5tLJt1dnlNZ1iAAZbP9wEJgMPlkCEAknuCtECEw7FjILdAcQa4ySEN1vArwHUs7cRYojquDgUyYZFK48qUCGPc7uMmlauz8sy4zSK3u3Gln9g6KrSf29y1H+TSbbadMG22d5T6BsCFpesHYId4QzoS/pEIlhbIPySWfoMQAnqAHh3Fz8gEDjtqOGwf9eTIhF3CnY8Uzisba3FPgZSovLEWCeel8QkGGKGs3LLW0qCjcBd+pT3OP2dipmY/PaEJBA9F/p1f0E/Ph875+TxB+4mpmY3nmNle1OAPuP9KNkOoX8MAAAAASUVORK5CYII="),("Gray","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAGFBMVEUAAACgoKAAAADfvqd8fHxUVFSyjXMTERAArvWNAAAAAXRSTlMAQObYZgAAARFJREFUKM9V0cGqgzAQBdDiH9yQ7uNU8/YK3Y+MPyDJD0Rw3dXr779rtH3tMAgebi4YL3UkiDRyeU0jmIAOEs73Dh6AQt0hnQEkVQ9XA2YKxY6GUANJGeB6haswm14BrmKqJ/pkWXFVtEAgTCXTuG7whN5u934pmRvHlmf6ZSzldhduWQe29nGL61jnHtfOXZpFlhOGRfaOlN8AqGPp/AHYwd7gj4R+JIylCe4fPEu/wREM8YD26Eh6RgZw2JFNIfu06hWBsIup8uFNeWV9Tqre4D2VN1Yjprw0PsEAI5SZm+acKjQU7sSvlMf556SIRJGflVBlK9sjbuF3fME6PB9xDM/nCXEdmBrZeI6I7EUV/gDoXlOpQvhhEgAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Sheep Head (Type 1)
# ========================================

echo "Uploading Sheep Head batch 1/4 (traits 0, 1, 2, 3, 4)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 1 "[0,1,2,3,4]" "[("None","iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="),("Beanie","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAADesC8AAACygyzig7/6AAAAAXRSTlMAQObYZgAAADRJREFUGNNjYGBYtWrVCgYgYPoaGhqGg7EKCEAM7qtfa+MbgAz98Kvx4Q8wGXA1cF1DGwAAvHUdFaOI7ngAAAAASUVORK5CYII="),("Blue Hat","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAAAAxfAUPVwwY9MkUpn///8Xb+CzKPBIAAAAAXRSTlMAQObYZgAAAExJREFUKM9jAAElCFBggAImQ0EgCA0UggmoGAuCQaACmoAoXMBZEAIQAsYIAYQlCGuY3KA6hKECKolQASOoAhdnYwiA6YAbwTAK6AQA8i0NMLnMBUEAAAAASUVORK5CYII="),("Blue Horns","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAAAAAAxfAkUpmUXFnp4iXeuZlDAAAAAXRSTlMAQObYZgAAAE1JREFUKM/tirsNwEAIQ6FIz2cCyARhg+y/VPBJVFnginuybAtDf1hlqircMmaqlPZELDyx2e0Z8+C92cM1h+AS8iXQeXVlggDypcOefGhhBSYgB3MPAAAAAElFTkSuQmCC"),("Bucket Hat","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAUPVwAAAD////U1NQeCbBYAAAAAXRSTlMAQObYZgAAADtJREFUKM9jAAImJShggAJFQShQIFpAxdkYAqACTC4wASO4DhQ9TIIIIARTgFACVYBQAncm3LGjgA4AALPMDRDZPu+xAAAAAElFTkSuQmCC")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Head batch 2/4 (traits 5, 6, 7, 8, 9)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 1 "[5,6,7,8,9]" "[("Capone","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAnJycAAADXzrjdAAAAAXRSTlMAQObYZgAAAC5JREFUGNNjYGBaBQQMQMC1NDQ0tAHEmEo8g2sVGDQwaAF1A0ECgxZEZAHDsAAAhfQbk6I91xcAAAAASUVORK5CYII="),("Cowboy Hat","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAAAAAACUXFlrTVl3RkyyhH5PPVAKPoY5AAAAAXRSTlMAQObYZgAAAFlJREFUKM9jAAFGQTAQYIABERclIAgNhPEZXcACSqoCaAJKAmCeAANjWrIxGAiAeY7IAqJARSKCYjABQ8FAiAlQM0JDQ8GmCAIFnCCmKkJsATkK5rRRMCAAAEwDEcWhVXTnAAAAAElFTkSuQmCC"),("Curved Brown Horns","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAACUXFl3RkxwD5rMAAAAAXRSTlMAQObYZgAAAExJREFUGNNjgAPGEBAZysDAthLEe+XAIAXEDOyrJjBUV01gYJBbvoShch6IMXMJQ1U5SKpsCYPcVpBioDz7BZB2eQcGRgcQg5VheAAAslgQppQv9PkAAAAASUVORK5CYII="),("Curved Golden Horns","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAAAADesC+ygyzp4iW2FyRIAAAAAXRSTlMAQObYZgAAAF1JREFUKM/tjsENgEAIBM8OwLUBuGtAtAGS678mIZH4sAA/7mMgy0Joby1M1TInt+k1OicF1cYdgaoHO7JkwBQxg7iVIZ6GArWCdVD4nesoVNLfnw8OSgZK3H59ogviAQfA0IBaBAAAAABJRU5ErkJggg=="),("Fedora","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAABTMG8AAAA4HUwse/DbAAAAAXRSTlMAQObYZgAAAEZJREFUGNNjYGBYtWrVCgYQ2BsaGgGimb6GhoYhMxZAGBoMO7iBjNCGGQx63FeBjKYEBu71IEZmAwPT/1AgCAObBzZxeAAAAv4b7SQW3IgAAAAASUVORK5CYII=")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Head batch 3/4 (traits 10, 11, 12, 13, 15)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 1 "[10,11,12,13,15]" "[("Mailman","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAkUpkAAAAUPVyUvX2gAAAAAXRSTlMAQObYZgAAAD1JREFUGNNjYGBYtWrVCgYgYPobGhoGYnB/DQ0NbUBm6F8FMhKwMriA2uEiS0GK9wNlokDmaAGlFjAMbQAATiUbPfY9QmIAAAAASUVORK5CYII="),("Pointy Brown Horns","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAACUXFl3RkxwD5rMAAAAAXRSTlMAQObYZgAAADVJREFUGNNjwASiYJIxgEHKAcRgm8AgNwHEkLrAwL4ExMh2YGB8CVKyFkiUMEAJAQYwMcwAAHIQBuXcyXwPAAAAAElFTkSuQmCC"),("Pointy Golden Horns","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAAAADesC+ygyzp4iW2FyRIAAAAAXRSTlMAQObYZgAAADdJREFUKM9jIAwYBdE4jCoCCAERRaCAkSNCgZMhkBRGKBFRBjIhShAKQEpAwsgsRoQZDKNgkAAAsRUDNeESnRIAAAAASUVORK5CYII="),("Rainbow Fro","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAAAAAAAki0gAxfDp4iWtKZWxHRj6e/wSAAAAAXRSTlMAQObYZgAAAG1JREFUKM/tjs0NgDAIRmED8Kd3cQJDHKCGBXroBsb9R9C2Vk28e/KFCy98AGSYmJGhgmxepFWms3dmi4jqHIpxq5mIjKox5IHtFpHSwFOEl8iRa2mfI8Bo1qSzEwYodB5lQCWg+hkBHwU/H7ED9CEVeXhOdWcAAAAASUVORK5CYII="),("Santa","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAAAAAAD////aPDbU1NSzs7OxRF5xtqTLAAAAAXRSTlMAQObYZgAAAGFJREFUKM9jAAFBGGCAAjFjMBAzFoDwGZMhAobJBAUSoQKiLk5KTkoqSqqiihAFIS4qSkoqQBioJAARcFICAiARGAQVcFFyAnKBKkIhAqEuQK6TipNqoCADqkMFGEYBXQAA18AUiMy3ysEAAAAASUVORK5CYII=")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Head batch 4/4 (traits 16, 17, 18, 19)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 1 "[16,17,18,19]" "[("Silky","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAACxHRgAAADaPDblLkmbAAAAAXRSTlMAQObYZgAAAEZJREFUGNNjYGBYtWrVCgYgYAoNDa0DMTiBjPgGGKNpAZTR/QPKWJsAZUxtgDKmARVzrQKC5SBtYDMeQBlMFQxQsIBhCAIAtFEYSeIKfXkAAAAASUVORK5CYII="),("Sun Hat","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAGFBMVEUAAADft1IAAACygywBAAGygy2zgyyygiwt9VdQAAAAAXRSTlMAQObYZgAAAGZJREFUKM/tzbENgCAQheGLG+AE+DgXELA2SGLv/sP4RCIJtaVfx8/lTmiAIiEDUh2msjXMfXBdQJFAtmw0zaic9ywNZPcRbwICA+Xpefv1DgtgVRVI/AriIldXcP7kFWkG3eT3uQv4TxEdSz1gaQAAAABJRU5ErkJggg=="),("Visor","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAAAAAAxfD///9RzuowY9OA/ye6AAAAAXRSTlMAQObYZgAAAC1JREFUKM9joBIQhAEBqICIszEE4BJgRNciGqQEAYpQBaFKUCCAbgnDKKATAADXjwhxIw22hAAAAABJRU5ErkJggg=="),("White Cap","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAGFBMVEUAAAD///8AAACf3flRzuqxHRjaPDaGIifUMawjAAAAAXRSTlMAQObYZgAAADpJREFUKM9jAAElCFBggAImF2NjQSAQggmoOBsbCoKAArUEmJSUUAXUy0NBICwNCKAqEECBYRQMDAAAXlYPxDEH70IAAAAASUVORK5CYII=")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Sheep Ears (Type 2)
# ========================================

echo "Uploading Sheep Ears batch 1/2 (traits 0, 1, 2, 3, 4)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 2 "[0,1,2,3,4]" "[("None","iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="),("Diamond Bling","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAxfCf3fkiSJbrAAAAAXRSTlMAQObYZgAAACNJREFUGNNjoCtwABEsDAyME0AMSQYGthQQI80BJoJQM0gAANAXAu1JLL1KAAAAAElFTkSuQmCC"),("Diamond Stud","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAABRzuqf3fkAxfD1N1m7AAAAAXRSTlMAQObYZgAAACFJREFUGNNjoAdwABEsQNwAYnAAcQGIwQ7EASAGK8OgBQAUogGZJVeZqAAAAABJRU5ErkJggg=="),("Gold Bling","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAACygyzesC/p4iXHD2p5AAAAAXRSTlMAQObYZgAAACxJREFUGNNjoCs4ACJ4GBiYN4AY1gwMbDkgRtoBBsYJIIYkEDuAGCwMgwQAAKzKBEH6IVfBAAAAAElFTkSuQmCC"),("Gold Hoop","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAADesC/p4iWygywWMD4DAAAAAXRSTlMAQObYZgAAAC1JREFUGNNjoAdoABEcDAxMYJ4CkGEAYigDGQIghiIDAyOYIQjEDiAGC8MgAQALcAGZnwuuxQAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Ears batch 2/2 (traits 5)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 2 "[5]" "[("Two Gold Piercings","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAADp4iXesC+/0+PiAAAAAXRSTlMAQObYZgAAABpJREFUGNNjoANgFACRggwMTAoghhJCZPADAF5gAImSV/7gAAAAAElFTkSuQmCC")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Sheep Eyes (Type 3)
# ========================================

echo "Uploading Sheep Eyes batch 1/5 (traits 2, 4, 6, 7, 8)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 3 "[2,4,6,7,8]" "[("Black Glasses","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAACf3fmF2+fnAAAAAXRSTlMAQObYZgAAACBJREFUGNNjoAdgDA0IDQWzsqZmTYAwJkAZQKkAhsELAF2sBoi6TPWPAAAAAElFTkSuQmCC"),("Confused","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAAAAD///8wY9PU1NQkUpmlxgFPAAAAAXRSTlMAQObYZgAAACxJREFUKM9jGAaAUVAAiSfIwCDiHIgk6yzAIKRsiCSgBBRQUkTWAjFjFGACANkKAlE1Ptk/AAAAAElFTkSuQmCC"),("Cyclops","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAAB1JREFUGNNjoCkIdYDQjKsmQBhsy5bARRBqBjEAAGQRBPHyQj4NAAAAAElFTkSuQmCC"),("Dork","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAACf3fkAAAD///8AxfCCQkOpAAAAAXRSTlMAQObYZgAAAChJREFUKM9jGNqASUlJiQGIFeAijsaCSkDMgBAQNARhZAFBMB4FRAAA9SgD5/qQtmEAAAAASUVORK5CYII="),("Face Painted","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAD///8AAADaPDaGIiexHRgAd/VpAAAAAXRSTlMAQObYZgAAAB9JREFUKM9jGHZAUACIUAQUGBTxCrgaAIkQA4ZRgAkAU8sCAFzFgE4AAAAASUVORK5CYII=")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Eyes batch 2/5 (traits 9, 10, 11, 12, 13)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 3 "[9,10,11,12,13]" "[("Fake Glasses","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAACBJREFUGNNjoAtgdRCFMKQmZDmAGZFT00LgInA1gw8AAER0BQWlV3LJAAAAAElFTkSuQmCC"),("Fearful","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABRJREFUCNdjIBcIOAAJBQUkLk0AAFQwAOF0Uq3NAAAAAElFTkSuQmCC"),("Fearless","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAAAAD///8AxfAUPVwGtYjRAAAAAXRSTlMAQObYZgAAACdJREFUKM9jGOqAEYgFkAVEBBgYHZEFhIEChsgCQkABRUwzRgEWAABnSQEiql7SnwAAAABJRU5ErkJggg=="),("Happy","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABRJREFUCNdjoAgYJAAJjwkQgiYAAM74AkGPa/xKAAAAAElFTkSuQmCC"),("Leafy Green","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAAAAD///9y4cMYbUUVq5Gzb1utAAAAAXRSTlMAQObYZgAAAC1JREFUKM9jGOKAUVCAQVAQSUBI0JFRUUQASUAokFFRFVnA2ZBRxViAYRQQAQBL7gKpc11X4gAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Eyes batch 3/5 (traits 14, 15, 16, 17, 18)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 3 "[14,15,16,17,18]" "[("Livid","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAADaPDa/NLVAAAAAAXRSTlMAQObYZgAAAB5JREFUGNNjoA9wEIAyBBwgNKuDKIQhOSHNgWHwAgB6SgJKNOqwvwAAAABJRU5ErkJggg=="),("Night Vision Visor","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAGFBMVEUAAAAAAADH242Ry2kki0gYbUUlrjsRTS0uPD9QAAAAAXRSTlMAQObYZgAAACJJREFUKM9jGNqAURAK4CIhyUpKyinhBbgFoDoEGEYBYQAAHNsFo8gXz6AAAAAASUVORK5CYII="),("Big Blue","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAAAAAAD///8wY9MAxfDU1NSzs7M1QfpOAAAAAXRSTlMAQObYZgAAADZJREFUKM9jGOKAUVCAQVAQSYBJTJBBMVEASYVpIINwKJIAs5ESg7GSAkKAxUmBwUWJYRRgAQBXoAOXwF4RywAAAABJRU5ErkJggg=="),("OMG","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAD///8AAABzxoNxAAAAAXRSTlMAQObYZgAAABVJREFUGNNjoC8QBUIwkARCuMggBgBYigCHfySWeAAAAABJRU5ErkJggg=="),("Small Blue","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAAAAD///8AxfDU1NSzs7N9AqmZAAAAAXRSTlMAQObYZgAAACtJREFUKM9jGG6AUVCAQVAQSYBJVIBBMRBZhQhQhSOSALORAoOxEsMowAIAWw4B/3P/5x0AAAAASUVORK5CYII=")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Eyes batch 4/5 (traits 19, 20, 21, 22, 23)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 3 "[19,20,21,22,23]" "[("Rainbow Sunnies","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAKlBMVEUAAAD////p4iWRy2kkUpmtKZUlrjsAxfAwY9O6Rp3esC/aPDaGIiexHRjD61CUAAAAAXRSTlMAQObYZgAAADFJREFUKM9jGNqA5/YiIbPkCpFIuMguRWUG80ZXhBKgAgZkBQyMygkMjK4TGEYBEQAAmnoIPpGtZsYAAAAASUVORK5CYII="),("Red Glasses","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAADaPDb///+f3flbDE79AAAAAXRSTlMAQObYZgAAACBJREFUGNNjoAdgDA0IDQWzqqZWTYAwJkAZQKkAhsELAIiMBsjrryLrAAAAAElFTkSuQmCC"),("Rolling","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABtJREFUGNNjoAtgdQiBMCQnzoQwpCauZBgKAAAqTQMxWBpKpAAAAABJRU5ErkJggg=="),("X Ray","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAG1BMVEUAAADU1NQnJydUVFSzs7OgoKB8fHwAAAD///9+jYp9AAAAAXRSTlMAQObYZgAAACdJREFUKM9jGFrAgL2cAYgUYHwmsxDBRpEwIyW4CqiAAhECo4AwAAAyZQixBvvRRwAAAABJRU5ErkJggg=="),("Sleepy","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAADaPDYAAACxHRiFjUoGAAAAAXRSTlMAQObYZgAAAB1JREFUGNNjoC/gdTCFMEwDrjqAGVoLVjUwDF4AAJfkBBFicZT9AAAAAElFTkSuQmCC")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Eyes batch 5/5 (traits 24, 26, 27)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 3 "[24,26,27]" "[("Spacey","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABtJREFUGNNjoC9gdQiBMKQmroQwJCfOZBjEAAAONgMxlwEXawAAAABJRU5ErkJggg=="),("Squint Right","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAACyjXP///9SqdirAAAAAXRSTlMAQObYZgAAAB5JREFUGNNjoC8QdRB1ADNsD9geADO0GrQaGAYvAACPDAP5rXCA5AAAAABJRU5ErkJggg=="),("Staring Contest","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABxJREFUGNNjoAtgdQiBMKQmroQwJCfORIgMYgAA/C8EhQfzzFEAAAAASUVORK5CYII=")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Sheep Nose (Type 4)
# ========================================

echo "Uploading Sheep Nose batch 1/2 (traits 0, 1, 2, 3, 4)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 4 "[0,1,2,3,4]" "[("Dot","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAAA5JREFUCNdjoDpgoqppAAE8AAPNbYZEAAAAAElFTkSuQmCC"),("Red","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAACxHRiN+9miAAAAAXRSTlMAQObYZgAAAA5JREFUCNdjoA1gpZZBAAINAAaOzYqnAAAAAElFTkSuQmCC"),("Gold","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAADesC+ygyzp4iXM8PRTAAAAAXRSTlMAQObYZgAAABVJREFUGNNjGDyABcbQhTE4GAYcAAAgKAA6oPTpgwAAAABJRU5ErkJggg=="),("Normal","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABFJREFUCNdjoDpgBRFM1DINAAK4AAgZ7pXcAAAAAElFTkSuQmCC"),("Dots","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAAA5JREFUCNdjoA1gpZZBAAINAAaOzYqnAAAAAElFTkSuQmCC")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Nose batch 2/2 (traits 5, 6, 7, 8, 9)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 4 "[5,6,7,8,9]" "[("Punched","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAACxHRir/4mtAAAAAXRSTlMAQObYZgAAABJJREFUGNNjGIRAEMZgYhhwAAALcgAU1IRuSQAAAABJRU5ErkJggg=="),("Triangle","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABVJREFUCNdjoCZgAhHsIIK/gUpGAgArrwCZZLzKJAAAAABJRU5ErkJggg=="),("U","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABJJREFUCNdjoDpgaQASzNQyDQApMwCIejoWBgAAAABJRU5ErkJggg=="),("Wide","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAACyjXMCmAU+AAAAAXRSTlMAQObYZgAAABNJREFUGNNjGIRAEMZIc2AYaAAAXx4AuAHt6rEAAAAASUVORK5CYII="),("X","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAnJycAAABUVFTztD9wAAAAAXRSTlMAQObYZgAAABVJREFUGNNjGDyABcbQhTE4GAYcAAAgKAA6oPTpgwAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Sheep Mouth (Type 5)
# ========================================

echo "Uploading Sheep Mouth batch 1/3 (traits 0, 1, 2, 3, 4)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 5 "[0,1,2,3,4]" "[("Beard","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAABUVFQnJycAAABIDEZpAAAAAXRSTlMAQObYZgAAACRJREFUGNNjGAqAMTSABcxo/X9FBMxQZRANADO4Vq1qYKAhAABKYgV/qKbb9AAAAABJRU5ErkJggg=="),("Big Smile","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAACBJREFUGNNjGFKANTTUAcxgW7UKwmBctRIqFxrCQAMAAMVABIfzxX3aAAAAAElFTkSuQmCC"),("Chill Smile","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABNJREFUCNdjoCFQEAAS8g8oMgMASzEBMGn9xVEAAAAASUVORK5CYII="),("Chinstrap","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAABUVFQAAACdgFLfAAAAAXRSTlMAQObYZgAAAB1JREFUGNNjGFLAQYuBBcwQYGEIADNYQ0MdGGgIALHXAcIZaItpAAAAAElFTkSuQmCC"),("Cigarette","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAAD////ft1JteCeNAAAAAXRSTlMAQObYZgAAABVJREFUGNNjGAogNADKeLUEIUIfAABEGwLZXNgLagAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Mouth batch 2/3 (traits 5, 6, 7, 8, 9)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 5 "[5,6,7,8,9]" "[("Cheese","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABZJREFUGNNjGFog1AFCM66agBChJQAA+RkCZmh5XfwAAAAASUVORK5CYII="),("Grillz","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAAD////p4iVEM/MhAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjGFKANTQUwmB7tRPCYNz1BMoIDWGgAQAAy/oEopz4M1EAAAAASUVORK5CYII="),("Missing Tooth","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAAD///+LK2OK52TNAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjGFKANTQUwmBbvRLCYFy1BCoXGsBAAwAAjNcD/iN6+sgAAAAASUVORK5CYII="),("Mustache","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAnJycAAADXzrjdAAAAAXRSTlMAQObYZgAAABZJREFUGNNjGAqAMTQAwmDRYmGgLwAAZf8A2SyaZ90AAAAASUVORK5CYII="),("Narrow Open Mouth","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAACGIiexHRhTeEvdAAAAAXRSTlMAQObYZgAAABRJREFUGNNjGFpAFMaQhDFkGWgKAB9QAEw967k5AAAAAElFTkSuQmCC")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Mouth batch 3/3 (traits 10, 12, 13, 14, 15)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 5 "[10,12,13,14,15]" "[("Neutral","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAAA9JREFUCNdjoDWw/0CRdgBKQQEwYvMazgAAAABJRU5ErkJggg=="),("Pouting","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAAA5JREFUCNdjoDVgokw7AAEeAAMmmXWWAAAAAElFTkSuQmCC"),("Smirk","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABJJREFUCNdjoCVQAGL+AxQZAQA7MQDw3RJz6wAAAABJRU5ErkJggg=="),("Teasing","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAACxHRir/4mtAAAAAXRSTlMAQObYZgAAABxJREFUGNNjGAqAhYERwmAMDYEKrWqAMrQYaAoA1mICBEG5ud0AAAAASUVORK5CYII="),("Wide Open Mouth","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAACLK2PMyNAqAAAAAXRSTlMAQObYZgAAABhJREFUGNNjGFKAMTQEyli1BM5ASNEAAACH0gPzIqMenAAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Sheep Feet (Type 7)
# ========================================

echo "Uploading Sheep Feet batch 1/4 (traits 0, 1, 2, 3, 4)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 7 "[0,1,2,3,4]" "[("None","iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="),("Blue Sneakers","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAkUpn///8UPVxkGBcRAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjGLGAF0Rw9TMtUAXzHJgDwMKqDpwBSKoARRECzKMjW7YAAAAASUVORK5CYII="),("Clogs","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAACUXFl3RkyyjXPfvqcAAADm9aNwAAAAAXRSTlMAQObYZgAAADBJREFUKM9jGAXDDBgwMDABkSCUG6ToIMiqJMzAJAwTEHZgYFU0QWhgAgowQAQwAQCTqwMCqj+T/gAAAABJRU5ErkJggg=="),("Dress Shoes","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAABrTVmLYHAAAABpcGB9AAAAAXRSTlMAQObYZgAAAClJREFUGNNjGJnAgZFBDESzujIGR4EY1xpMF4No5qiGawvADAaGA0AKAH+CBpRB4MtmAAAAAElFTkSuQmCC"),("Elf","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAACxHRiGIicAAAATERAFVo93AAAAAXRSTlMAQObYZgAAADZJREFUKM9jGAXDDAgwMDABKUUIz5hBUUDZgEmQRUkQImBkoCjALMwkCFfPLCgowGAoKIjdNAB7PwJ5dZ0C2wAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Feet batch 2/4 (traits 6, 7, 8, 9, 10)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 7 "[6,7,8,9,10]" "[("Gray Shoes","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAB8fHxUVFQnJycAAAAL5v8lAAAAAXRSTlMAQObYZgAAAC5JREFUKM9jGAXDDBgwMDADkRKMbySgxMCsCEIQ4KwowMBiJIjQwAwUYIAIYAIAbzACN3lvSakAAAAASUVORK5CYII="),("Green Sneakers","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAYbUX///8RTS2SZfaAAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjGLGAF0Rw9TMtUAXzHJgDwMKqDpwBSKoARRECzKMjW7YAAAAASUVORK5CYII="),("High","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAABrTVmLYHAvriRzAAAAAXRSTlMAQObYZgAAACRJREFUGNNjGJnAgZGBDUSzujIGSIEYbA2MC8AyYg2sC5AUAgBLcwNfMjTmaQAAAABJRU5ErkJggg=="),("Ice Skates","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAB8fHwAAAD////aPDa68bjrAAAAAXRSTlMAQObYZgAAAEBJREFUKM9jGAXDDBgwMDADKSUFCJfJxclYQMVFQVhYACKgpKQkKKSkpCAoCBUQFjZkYDQ0FoCbICgoyMAIlQYAw+IEUFxH0moAAAAASUVORK5CYII="),("Purple Sneakers","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAACtKZX///+LK2PExSGQAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjGLGAF0Rw9TMtUAXzHJgDwMKqDpwBSKoARRECzKMjW7YAAAAASUVORK5CYII=")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Feet batch 3/4 (traits 11, 12, 13, 14, 15)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 7 "[11,12,13,14,15]" "[("Red Sneakers","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAACxHRj///+GIifO3OvTAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjGLGAF0RwtTItUAXzHJgDwMKqDpwBSKoAQ9ECwqXLH3QAAAAASUVORK5CYII="),("Roller Blades","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAAAADaPDYwY9P///+GIifs5m8RAAAAAXRSTlMAQObYZgAAAEBJREFUKM9jGAXDDBgwMDAzMAoKCkC4jMaGTgzCxoKKjooQAUFBQVVFQUGhIKcgiICQiJAAI0gaBlRVVBWYoNIA02sFvbgiUlcAAAAASUVORK5CYII="),("Slippers","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAAD////U1NQrJtYdAAAAAXRSTlMAQObYZgAAAClJREFUGNNjGLGAG0SE8IsyrwbSjC9DqkJBAuyrVr5a5QBksIYCgQMDAIWHCAZ0ivZ6AAAAAElFTkSuQmCC"),("Snowboard","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAAAxfCIUzjXAAAAAXRSTlMAQObYZgAAACRJREFUGNNjGMlABEZJhgawhjCGpjCwrXLgamBaNYGBMRQMHABaSgbvYKSrowAAAABJRU5ErkJggg=="),("Striped Socks","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAACxHRiGIifU1NT///8JCi5WAAAAAXRSTlMAQObYZgAAAC1JREFUKM9jGAXDDBgwMDADKWUYX1FAiYFJEISgwMQBqMIFrh4oIwBUJYjdNABfAQHgRgVXngAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Sheep Feet batch 4/4 (traits 16, 17, 18)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 7 "[16,17,18]" "[("White and Gray Sneakers","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAD///+goKDSb8EQAAAAAXRSTlMAQObYZgAAACNJREFUGNNjGJmggYmBE0RzdTEtUAUxOB2YAsAyog6sAUgKAVcPAyyjM3sZAAAAAElFTkSuQmCC"),("White Boots","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAAD////U1NQrJtYdAAAAAXRSTlMAQObYZgAAAChJREFUGNNjGJmggZmBD0TLzWdfYgdmTGBfApapmyAPYYQGiIYwMAAAhjIGcCT0leIAAAAASUVORK5CYII="),("Yellow Sneakers","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAADp4iX////esC/HqtVrAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjGLGAF0Rw9TMtUAXzHJgDwMKqDpwBSKoARRECzKMjW7YAAAAASUVORK5CYII=")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Wolf Fur (Type 9)
# ========================================

echo "Uploading Wolf Fur batch 1/2 (traits 0, 1, 2, 3, 4)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 9 "[0,1,2,3,4]" "[("Brown","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAADfvqeyjXOUXFkAAAB3RkwnJye5rIxEAAAAAXRSTlMAQObYZgAAAOlJREFUKM9d0UtywyAMBuAsuADuY59fNAeQSNcEK9m3uAfoeHz/K0QmjmGihZj5RhIaOFhoarlGDpYcGoxIptQBB1VIBwKAOsjew/sOLhXaDOcrDLGDAYbhFd53OG7QDa3RX7vG0MBV+HyFObSW/7WA26rjl8Evy/TsEPz4DwLFHXjwEJJz2oDYVmMi2YGO/g0m0xPAHsS8D8nMA4tJTBucrZ+pUJgeMn6DBVIkcnzAKYOEZg4FqbacRqDwIkE51Io4AbNcS9w+cYkT41ZuywZXiX9jLGKn8ytkjqpKlDld6js6VcuqTi0d7qKuM66LilVzAAAAAElFTkSuQmCC"),("Black","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAAAAB8fHxUVFQzMzP62w08AAAAAXRSTlMAQObYZgAAANBJREFUKM9d0dGtwzAIBdBmA9+YBYLfAi4sgGD/mR5x3dgqHyQ68sVIfmWhrD6q9myHLCApqbqBd0BigxAR3aAyC/MG54A14+ABzTZokth/4XrgPWEbOmq/9q624Bhw/QL1FTnvA75WpZ5QPfBNhJx8qag94I0lNKxMUM/VXDUe0Df/SQq+IM6i7s+Q6t48UqxMsMy7knZ8hEw8JCjMbS5WRUPJO0kZkfwRckSH908ECQGy+YgwuICACQgDGUV+D76hugFQrV5OLiOC7MCBbK9/btEuQ7KP2ysAAAAASUVORK5CYII="),("Cyborg","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAHlBMVEUAAAAAAADU1NSzs7N8fHwmJiZUVFTaExM+Pte2FSj4QyJcAAAAAXRSTlMAQObYZgAAASVJREFUKM9dj7FugzAQhskb+EIodCyoVVYwaWeE5c7GQLLSUHdGaVplLFNXxr5tfTYmVf/hbH/6dOfzvBUA8XQAAA8NWDngcWKFZwPwpJUwRdEqB38AOEXCcwkEpTRtyAL8OKZxzK5gbUC+gFVsQFL8AQnVMP0P7haQOXBtakLcP8E37wTsNtF2FAbcr7+3KK3GGdTV+OVhIn1FgVUoGEVyDfq8QsEoMn+JH0p6EO4fkpo0PXHAjm25A0eaZDShfd/NQKksy7hS3O3rP0pWHtEgM+B1U8tSG8KSDW/3bc3qvpN2cvgRnM/7z5YXO0kM4EHT1O+tuoWdsD0mpWQ5NSEJhBn7OvBCdYO6ED9FIX+ebrDkb/CDxobxAbAwCC/YFHRMAaIvv1CnSEBkTjEbAAAAAElFTkSuQmCC"),("Demon","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAGFBMVEUAAAD/YEUAAADqJhfJABiKGTRgFzb/o6OFcHZiAAAAAXRSTlMAQObYZgAAAQtJREFUKM9dz8FOwzAMBuAqb5AVOGdpOs6NzR4gduFMFuAMankAJLTXn5NMzTSrl3z1HztdLmuNfN1WSvtOTbsGe5S/bmot7vPH2t/UYFwAANcGg9agNTfYF0DThhToww30IOjvYbfBtEG7NFe+1FzH5urloGqXKvB0D4uXcH3Q8J0bSFYdoIB7ETgRR9VDziiGd/2IgEGdIBagXgMjz2acTQYkWY0Q2SiqgJN+AJHYOV8ASAMSYehcKGOJemKRDWbJEyb0lgq4VyAGThzSdbHjAMi4kJeGEjk6gEQr+2gKuBABFh5TqGe7hkj+kA5rDaiUwocbZx7nCs//b9Hac/o7f9WEstZKLlc+XgDimToFb45F8wAAAABJRU5ErkJggg=="),("Golden","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAGFBMVEUAAAD/9cz/1zgAAADvtBazfBz///9/Vx4OPYF3AAAAAXRSTlMAQObYZgAAAPJJREFUKM9d0cFOwzAMBuBJeYIUEOf9Meya1Z12dwycoYEH2KB3pPb9l2VtE80HR/pkx1ayScG+5BytS8mgQAeflCoQxwytQAFQBa21sLaCfQZawdgMTaigQUJ3Dw8rbBcol+aox16jKWAyPN/D6ErL/7VAyqrdS4Iv0fPSofi0T4TXYQVpLJT0z89AklYTIl2BtvYRSfoFIBYkQmEZK9KIJgl+hjciFYrk+pt0HxDFb9Qg5xvsWtD7MIr7GXxu2XVAPE3q+ORyReiBUQ8xzJ84hV5wjMdphoOG7y5ETaexLq8RmJmoFb/P72iYU2Y2nNLmAqlBNWjrQUErAAAAAElFTkSuQmCC")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Wolf Fur batch 2/2 (traits 5, 6, 7, 8)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 9 "[5,6,7,8]" "[("Gray","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAADU1NSzs7N8fHwAAABUVFQzMzN30vgtAAAAAXRSTlMAQObYZgAAAOlJREFUKM9d0UtywyAMBuAsuADuY59fNAeQSNcEK9m3uAfoeHz/K0QmjmGihZj5RhIaOFhoarlGDpYcGoxIptQBB1VIBwKAOsjew/sOLhXaDOcrDLGDAYbhFd53OG7QDa3RX7vG0MBV+HyFObSW/7WA26rjl8Evy/TsEPz4DwLFHXjwEJJz2oDYVmMi2YGO/g0m0xPAHsS8D8nMA4tJTBucrZ+pUJgeMn6DBVIkcnzAKYOEZg4FqbacRqDwIkE51Io4AbNcS9w+cYkT41ZuywZXiX9jLGKn8ytkjqpKlDld6js6VcuqTi0d7qKuM66LilVzAAAAAElFTkSuQmCC"),("Skeleton","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAADU1NQAAABUVFSzs7N8fHwmJibTOhb/AAAAAXRSTlMAQObYZgAAAOtJREFUKM91z01uxCAMBWDEDWxD1+Bkujck3adDZ0+iOUC7yP2PUPJTiCrNAyHx6SFhVcKunkf6z3Lo1OCWXNGvCyyBOT4vIFAyNuhgC70GDUfwP8wV8n63rWF3yBWUz1sBXAMpQKaBpgLyuMAUYzQ/qqUvjUdQrfGRUvp+8uXr67oKtHE9WcgEMFfId4mT5DqeH0DKHm0FKQ2RCOGEnowMZJaMfyCxLDMCuvPJAiIgweIptzcyKRq2weMJgyyTsHXa75UO+0j3DdQBjHNK7+J8OED7OXXIwB4P8IDMDOTJadynZ97esWalnfoFyskoXjMg55wAAAAASUVORK5CYII="),("White","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAADU1NQAAAD///+zs7OgoKB8fHy2ACS8AAAAAXRSTlMAQObYZgAAAN1JREFUKM910dGNwyAMBuCIDWyn9xxMO4CxOgAcC1SXBbr/EmfTlKBKtSIn+hT/WGKx4u3svSJaC3DC1b/jOkFBZmgTNGhlnSACNHs+4cwI0AHqBKsDfocyYIT2mjf1mjYNHX4+4ZkHpKf/8HuGxLvBH0EdE/qAi6jgAFJVkHFOEAcSgQGiKi71DUomRCMkESmBCW4HrDZPUiTXl8SLEigUQMJjsaQC8qBcdOsj96haaIfMlB0iVrVl7XqW5BB2rKS3ctsPuAK2iAXsHdQhETKzSKIt9dDAbJ05sLXlH99sKB2+O3PtAAAAAElFTkSuQmCC"),("Zombie","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAHlBMVEUAAADd4c4TFQ3CyaeVomhsdkk7QCjNQGHybX0AAADJ4bO/AAAAAXRSTlMAQObYZgAAAQVJREFUKM9d0cFOwzAMBuAqbxAKnLOkG+fFpg8Qu0McacMQR0TKAyAh7Q125ZGXpl1SzQdH+eTfipQqllalpzI2NgEFGlBRcQVktR5eqwIM7emP/8sOKWE8f5aJTQR59HmHkBPI2q2ghoj2Fu4y7DPkpalWT0/3uoBI8HgLwZbI1zRAnEea5wgDcX9NMLzJBwR0GaiWwMidWgApPo0+AmfAvbznc8D+CkASD6fvvMQQ1dT9DOTUAh0i09GjXTLNAYih8+xe1AytAWQMZPvfOdI2AJ5GtupJpQnXAwTeeleZCcToeoKd341u/tUtu/fGeY6nkBMYclprRENqI1NE69i1Fjq26gLc1jdBSLXPzQAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Wolf Head (Type 10)
# ========================================

echo "Uploading Wolf Head batch 1/1 (traits 0, 1, 2, 3)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 10 "[0,1,2,3]" "[("Alpha","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAADp4iWxHRjesC/aPDaGIiey0+b9AAAAAXRSTlMAQObYZgAAADVJREFUKM9jAAFmAUMBQwYkIOSo5KgigOAzB4kqqQg5IqkwVQxSDAKqQCgxNhYUZBgFwwwAACa2BCnRkiorAAAAAElFTkSuQmCC"),("Beta","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAADesC/p4iWygywWMD4DAAAAAXRSTlMAQObYZgAAACdJREFUGNNjYGBgNGKAAKObBmCaSTrtEpjBnDu7Gsxg3Jb7lmFEAgB10gZbpLr1hQAAAABJRU5ErkJggg=="),("Delta","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAnJydsiL5QWZY3dEemAAAAAXRSTlMAQObYZgAAACZJREFUGNNjYGBgUmKAAMGZAmCaWS0tGcxgnDlzJoQRGhrKMCIBALIqBJ2aDbFxAAAAAElFTkSuQmCC"),("Omega","iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Wolf Eyes (Type 12)
# ========================================

echo "Uploading Wolf Eyes batch 1/6 (traits 0, 1, 2, 3, 4)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 12 "[0,1,2,3,4]" "[("3D Glasses","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAABDP2RQWZYwY9PaPDYkUpmxHRgkvYJJAAAAAXRSTlMAQObYZgAAACpJREFUKM9joBsQUhIUFFRSEoQLMIYGMqYlMjAIwAWMDRldHLEKjIIBAgCzEQQyLJg4UgAAAABJRU5ErkJggg=="),("Calm","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABlJREFUGNNjIBc4sEAZIawOEEYEawPDsAMAeYwBu2eqK7sAAAAASUVORK5CYII="),("Challenged","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABhJREFUGNNjIBcEMDpAGKKiUBExMYbhBwDMUwDo9EJHjwAAAABJRU5ErkJggg=="),("Closed","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABNJREFUCNdjIAZMaQAS34EE/QEAMSUCjGzFT/EAAAAASUVORK5CYII="),("Crossed","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABVJREFUGNNjoBiEijpAGJwSDMMPAACvVADMF486XAAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Wolf Eyes batch 2/6 (traits 5, 6, 7, 8, 9)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 12 "[5,6,7,8,9]" "[("Curious","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABZJREFUGNNjIBeEiEJoxiliDgjGsAMA7gACQHP1B3QAAAAASUVORK5CYII="),("Deep Blue","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAAAAD///8wY9NRzuok7Q52AAAAAXRSTlMAQObYZgAAACZJREFUKM9joB9gFGAQRBEQVmRUFkAWUDFkNFFAFhAUAKFRMHAAAFMpAXckuR9KAAAAAElFTkSuQmCC"),("Downward Gaze","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABxJREFUGNNjIBeEsDqAacaVUhMgIjM4GxiGHQAAn9MDD9NbETgAAAAASUVORK5CYII="),("Expressionless","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABBJREFUCNdjIBo8bmAYAAAAo8IBZAeCbMMAAAAASUVORK5CYII="),("Flashy Sunnies","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAADaPDbWXjMlMaJrAAAAAXRSTlMAQObYZgAAACRJREFUGNNjIBOwhoaGBoAYjD/lJ7CAGSulIAyGEFYHFoZhAgA+eAT3cXb5TAAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Wolf Eyes batch 3/6 (traits 10, 11, 12, 13, 14)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 12 "[10,11,12,13,14]" "[("Full Moon","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAADp4iUCHEfGAAAAAXRSTlMAQObYZgAAABZJREFUGNNjIBeEsgZAGFGsCxiGLwAAdc0Bqi7falEAAAAASUVORK5CYII="),("Hipster Glasses","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAACGIiexHRjF5O0AAADncVZCAAAAAXRSTlMAQObYZgAAAC5JREFUKM9joBtQUhQUFFJSEoQLMBobKhobMjAIwAVcDIEIWUBQEIhAAqNggAAA/9cDGdCkuJEAAAAASUVORK5CYII="),("Mascara","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAAAAD////31GjesC/wTwMfAAAAAXRSTlMAQObYZgAAACdJREFUKM9jGDjAyMjIICAggCQgKMggKIgkwGQowuAorMAwCgYMAADySAFEqKSTQQAAAABJRU5ErkJggg=="),("Leftward Gaze","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABVJREFUGNNjIBeIsEIZkWIODMMXAACu1gDJQdqGPQAAAABJRU5ErkJggg=="),("Lovable","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAAA9JREFUCNdjIACUUAj6AwAxogBn9QqdoAAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Wolf Eyes batch 4/6 (traits 15, 16, 17, 18, 19)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 12 "[15,16,17,18,19]" "[("Narrow Dots","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAAA9JREFUCNdjIBqIMAwEAAAJ2AAVPM/xJQAAAABJRU5ErkJggg=="),("Non","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABlJREFUGNNjIBsIQCjGENEACCuStYFh2AEAZ9gBqbVtzwEAAAAASUVORK5CYII="),("Pouncing","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAADp4iUCHEfGAAAAAXRSTlMAQObYZgAAABRJREFUGNNjoBg4MEIZU8QYhh8AAMbZAOyq9yoHAAAAAElFTkSuQmCC"),("Triangle","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAAAAD////esC/p4iXz4cM1AAAAAXRSTlMAQObYZgAAACBJREFUKM9joB9gFGAQRBEQFgAiZAUqAgwiigyjYBABAFRUANOQf3MAAAAAAElFTkSuQmCC"),("Restless","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAD///8AAABzxoNxAAAAAXRSTlMAQObYZgAAABhJREFUGNNjIBeIMDpAGJlsE+AMhNRwAQA/rAKpjHjtFQAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Wolf Eyes batch 5/6 (traits 20, 21, 22, 23, 24)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 12 "[20,21,22,23,24]" "[("Rightward Gaze","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABZJREFUGNNjoBiEsDpAGEu5AhiGHQAAWNkBmUCD1MMAAAAASUVORK5CYII="),("Sus","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABlJREFUGNNjIBcEsEIZLAwOEEYm2wSGYQcAW1oBmREaM9oAAAAASUVORK5CYII="),("Simple","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAABJJREFUGNNjoBhEsDYgGMMOAAB2rAG7OrJocQAAAABJRU5ErkJggg=="),("Standard Sunnies","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAB8fHwEsXMZAAAAAXRSTlMAQObYZgAAACRJREFUGNNjIBOwhoaGBoAYjKliASxgxlRJCIMhhNWBhWGYAAA5FAPF0zfHvQAAAABJRU5ErkJggg=="),("The Intellectual","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAAD///8AxvILX77fAAAAAXRSTlMAQObYZgAAACNJREFUGNNjIBOwhjCGBoBZleETWMCMXLYLEIYIowMLwzABAG3FBAShPbp8AAAAAElFTkSuQmCC")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Wolf Eyes batch 6/6 (traits 25, 26)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 12 "[25,26]" "[("Unibrow","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABJJREFUCNdjIAb8bwASjgwDAQDWGwHBdn5dmwAAAABJRU5ErkJggg=="),("Wide Dots","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABBJREFUCNdjIAY4NDAMFAAAXGAAwbIThh4AAAAASUVORK5CYII=")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Wolf Mouth (Type 14)
# ========================================

echo "Uploading Wolf Mouth batch 1/3 (traits 0, 1, 2, 3, 4)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 14 "[0,1,2,3,4]" "[("Brown Nose Smirk","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAAAACGREumXFiyLQuqAAAAAXRSTlMAQObYZgAAABtJREFUGNNjoAvg/wBlcC2AMoQaoQzWEIbBDADFWQKWe1o0aQAAAABJRU5ErkJggg=="),("Flared Nostrils","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAB8fHwEsXMZAAAAAXRSTlMAQObYZgAAABxJREFUGNNjoAtgDIAy2FLQRRgc0EVYWBgGDwAAFIEBpqhDJG4AAAAASUVORK5CYII="),("Frown","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAA8SURBVHgB7dAxCgAwCENRvf+h06VbhxIVXP7bBIOSCADAsjR29Ubl5Cek7iOKRaPH3QrVyLbpMwMAAJQcVNII/nWG3ZYAAAAASUVORK5CYII="),("Gray Nose Smirk","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAABUVFQAAAB8fHybc42tAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjoAtg/wJlsIZAGYwBDVBWE5RmWsEwCAEALuUDUsAgC00AAAAASUVORK5CYII="),("Howling","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAA3SURBVHgB7dCxDQAwCANBk/13dgZIhQKi4K82ErYEABgWiaw/bstY7yN7OBran0x47/YAAKDTBWMEBgBVGLRtAAAAAElFTkSuQmCC")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Wolf Mouth batch 2/3 (traits 5, 6, 7, 8, 9)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 14 "[5,6,7,8,9]" "[("Narrow Smile","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABVJREFUCNdjIBfYwQkZEOEJ4VIdAABorAEgjL+rgAAAAABJRU5ErkJggg=="),("Neutral","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAQMAAABJtOi3AAAABlBMVEUAAAAAAAClZ7nPAAAAAXRSTlMAQObYZgAAABVJREFUCNdjIBfYgQgZEMEBYdEGAAAw0gB/IiGr2QAAAABJRU5ErkJggg=="),("Mischievous","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAABASURBVHgB7dE7DgAgCATR9f6HXls/FWI0mnk1hEmQAACXlcCs5zVH9tMBQ4TSx1e5SbD6qKMBWw4/+QIAAPCXCsbCCQB95XMPAAAAAElFTkSuQmCC"),("Red Nose Smirk","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAACGIicAAACUXFlvTMdOAAAAAXRSTlMAQObYZgAAAB5JREFUGNNjoAtg/wJlsIZAGYwBMLkmKM21gmEQAgDghgLa1TaQZAAAAABJRU5ErkJggg=="),("Relaxed","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAABUVFQAAAB8fHybc42tAAAAAXRSTlMAQObYZgAAAB5JREFUGNNjoAuQ/wtliKVCGawhMLkGKM20gGEQAgAKnwMTkr3sIAAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Wolf Mouth batch 3/3 (traits 10, 11, 12)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 14 "[10,11,12]" "[("Smoking","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAAAACzs7N3RkzaPDZbArQ5AAAAAXRSTlMAQObYZgAAACtJREFUKM9jGLyAiaAAgwIDg6CgAIoSTAFGQTQtDALIAizGxoaCDKMAOwAAzGwBezfyYbcAAAAASUVORK5CYII="),("Tongue Out","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAAAACLK2PaPDZ8fHwwqgYNAAAAAXRSTlMAQObYZgAAADNJREFUKM9jGGJAxEUAhS8gKCgggCLAKMiAKgCGSIBRSEkQ1VBhZQFUAWZldHsVGEYmAABo/wHvITi3ZQAAAABJRU5ErkJggg=="),("Wide Smile","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAB9fX1rbxj5AAAAAXRSTlMAQObYZgAAACFJREFUGNNjoCVgWwJlsIZAGY4BARCGg4MDhCEayjCYAQAb0AMPL3oWpgAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

# ========================================
# Wolf Neck (Type 15)
# ========================================

echo "Uploading Wolf Neck batch 1/3 (traits 0, 1, 2, 3, 4)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 15 "[0,1,2,3,4]" "[("None","iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="),("Bandana","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAACxHRjaPDaGIic8TUzRAAAAAXRSTlMAQObYZgAAADZJREFUGNNjGHjADCP5wQzGAwzmEMYGhusQxtKwGIjSrKgCCENq5QEIg2051BTGGJh5BdR0HACoFggfrfG60wAAAABJRU5ErkJggg=="),("Bowtie","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAADPFxGdHCL8OTPmGSr0AAAAAXRSTlMAQObYZgAAACNJREFUGNNjGArAhvkAhHHrVwGEEbYyAMKIioIyRFkdGGgAAIFjBfERQcIxAAAAAElFTkSuQmCC"),("Clock","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAAAAAAD///8mJibU1NQAxfCf3fniSfVsAAAAAXRSTlMAQObYZgAAAERJREFUKM9jGAWs6AJs6KKsUFEESADiADgPyklAMQTD4GDjBFQBExMDFD6jk5EjqoCSsSKaCiVUFQwiKgKoAoyCVA0cAGd+BTKRuF0RAAAAAElFTkSuQmCC"),("Diamond","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAGFBMVEUAAABDP2RRzuoAxfBsiL7///+f3fm96eYt/Nz0AAAAAXRSTlMAQObYZgAAADlJREFUKM9jGAWYQACIGUkQgHIEUA0BiaEqEUCzRxCNz6SqgCqgWlyGKuBkqoIqwJzmgGaIM1WDAgCs1ANUMV5SlAAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Wolf Neck batch 2/3 (traits 5, 6, 7, 8, 9)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 15 "[5,6,7,8,9]" "[("Dress Tie","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAADaPDaxHRiGIieWWlKBAAAAAXRSTlMAQObYZgAAAB1JREFUGNNjGMTAgOEAhMEbDhVh/gOTS6AaAz8AAAFFBbQwGANWAAAAAElFTkSuQmCC"),("Flowers","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAAB+QJQAUZ30XizPFxHs4wAAsCrBqxd6AAAAAXRSTlMAQObYZgAAAFFJREFUKM9jGCFAAc4KAJNMSnABUzDJCFfBbAymBAXgKkzApCPCNBcHIMHighBgEQBpdEAIMAoyMLAaGyC5QFCBLTQYyoY6IS0VzZFsDIMNAACDCQVI4lQm7gAAAABJRU5ErkJggg=="),("Gold","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAACygyz31GjesC/p4iXl/SAkAAAAAXRSTlMAQObYZgAAADZJREFUKM9jGAUQIIDEdoASCEl0FQpgAk0FM7IKQyBmRLaACYiFkAUYHRgYDVDcICwkwjDIAACrXQIFuHNyTwAAAABJRU5ErkJggg=="),("Mask","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAD1BMVEUAAAAAz+z///8AxvJeicGHiYOQAAAAAXRSTlMAQObYZgAAACtJREFUKM9jGAWYQAGImSgUMHRgYDFAFmA0cXEWQLFGWNAQ1V5GYwGGQQYA7Y8Ck6qdnCcAAAAASUVORK5CYII="),("Pearls","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAADFBMVEUAAAAwY9MAxfAkUplGHsLCAAAAAXRSTlMAQObYZgAAADJJREFUGNNjGHjACCaZGBjYINwDDLwQEQcGCZiICUTpBIYECKOS7QKEwZ4LMwYoQAMAAH48BapPurmuAAAAAElFTkSuQmCC")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "Uploading Wolf Neck batch 3/3 (traits 10, 11, 12, 13, 14)..."
cast send $TRAITS_ADDRESS "uploadTraits(uint8,uint8[],(string,string)[])" 15 "[10,11,12,13,14]" "[("Secret Society","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAG1BMVEUAAAAmJiZ8fHwAAACGIiexHRizs7NUVFT///9CtDXHAAAAAXRSTlMAQObYZgAAAEJJREFUKM9jGAUsYNIBIcAKJgNwqIBLsiIb4gDFCEMMBU1RrGEWKhJGEWDUUFNEFShKKkQVUFNTxG8Gg6GgAQMtAQAPUQX5XIuKQgAAAABJRU5ErkJggg=="),("Sheep Heart","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAACxHRjesC/aPDb31GjWXjOwiADrAAAAAXRSTlMAQObYZgAAADBJREFUKM9jGAVEACYgVkAWYAFiB/wqQAgFKDMqoAoYigqgCQiiCTALorvEgIG+AAA21QHBYNpakgAAAABJRU5ErkJggg=="),("Silver","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAD////U1NSdrAhLAAAAAXRSTlMAQObYZgAAACtJREFUGNNjGESAA0I5MLBAGA1YRCQgjAQGBQhDgGEChKHC5ABhcM6kppsAl3oD2R6TEoEAAAAASUVORK5CYII="),("Sunglasses","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAFVBMVEUAAACGIiexHRgkUpkUPVzesC+ygyyPHH7yAAAAAXRSTlMAQObYZgAAAEtJREFUKM9jGKGADYmJLsAKIUlRwZAIxIwJSAKBIIEAJAFRkA4BJAEwG6+AEggoIAmIGAsImyCrAPKAYsgqHBkYXZAFGIEcQfLDCQDEhgTz1mA1JwAAAABJRU5ErkJggg=="),("Teeth","iVBORw0KGgoAAAANSUhEUgAAACAAAAAgAgMAAAAOFJJnAAAACVBMVEUAAAAAAAD///+D3c/SAAAAAXRSTlMAQObYZgAAACdJREFUGNNjGESADUwyOTCwQPgO+EQEwAwgFQFhtIY2QBgcHdR0EwB3ZAPDpQXUNQAAAABJRU5ErkJggg==")]" --rpc-url $RPC_URL --private-key $PRIVATE_KEY

# Wait a bit to avoid nonce issues
sleep 2

echo "All traits uploaded successfully!"